### ISSUE TITLE
Yahoo GET me/friends pagination not working

### ISSUE THREAD

**Issue by SkyHacks** [MrSwitch/hello.js#376] opened 2015-12-09 18:42 UTC
I started with 3 demo contacts in my Yahoo account and hello.js returned them all in the data array. Once I added a 4th contact, it began paging the results. I have attempted to follow the steps outlined in the paging example but anytime I pass in the resp.paging.next path to the callback, it returns a null query like this:

```
{
 query: {
  count: 0,
  created: "2015-12-09T16:11:04Z",
  lang: "en-US",
  results: null
 }
}
```

I have checked that the 'next' path is correct and the callback works for the first few contacts so I believe that everything is setup correctly. I am recursively calling next to try and get all of the contacts. 

I'm in the middle of trying to debug the issue, but here is the function that I'm working with:
```
getYahooFriends('me/friends')
var friendsArray = []

function getYahooFriends (path) {
  hello(network).api(path, {limit: 100})
  .then(function (r) {
    friendsArray.push(r);
    console.log(path,r);

   if (r.paging && r.paging.next) {
      getYahooFriends(r.paging.next);
    }  else {
      defer.resolve(friendsArray);
    }                          
  }, function (err) {
    console.log(err);
    defer.reject(err);
  });
}
```

I get the same result from the test page --> https://adodson.com/hello.js/tests/#hello-x-api-path--method--data--callback--

The first page returns 3 contacts but the next button returns the null query.

Here is a screenshot of my contacts:
<img width="540" alt="screen shot 2015-12-09 at 9 12 56 am" src="https://cloud.githubusercontent.com/assets/10717361/11690689/1fab9aec-9e55-11e5-87f1-a00c00cc4985.png">

**Comment by MrSwitch** [comment] 2016-01-06 21:14
I believe this is a duplicate of #375

**Closed by MrSwitch** 2016-01-06 21:14 UTC
