### ISSUE TITLE
Upgrade Facebook Graph API v2.x

### ISSUE THREAD

**Issue by AmarildoLima93** [MrSwitch/hello.js#175] opened 2014-12-24 12:37 UTC
Check this url "https://developers.facebook.com/docs/apps/changelog?locale=en_US"

**Comment by renholm** [comment] 2015-03-11 10:18
Just click "Settings" and the "Advanced" and make your app default to v2.0. 

I think we can close this?

**Comment by MrSwitch** [comment] 2015-03-11 11:31
Thanks @renholm that's valuable info.

If anyone finds any incompatibilities with this approach please comment. Otherwise i'll close this in a couple of days.

**Comment by renholm** [comment] 2015-03-11 12:14
Hold on, not sure that this works. Facebook is still complaining about the app not being upgraded yet. Not sure really what they mean. 

The setting I changed was to default unversioned calls to 2.0. 
> Use Graph API v2.0 by default
> Unversioned API calls will be treated as v2.0. People who log into your app will see the new Facebook Login dialog.

To my understanding hello.js is doing unversioned calls. So it should work. Maybe hold on and see if the status changes.

**Comment by dasper** [comment] 2015-03-12 22:32
Come April 30th they will be removing support for their 1.0 calls. This includes big changes to the data returned for friends. I believe the default will be only returning friends that have also accepted your app's permissions. Furthermore, if you want their full friends list, you will need to use the me/taggable_friends call and you will need to have this approved by Facebook first or you will get this error:

> (#10) To use taggable_friends on behalf of people who are not admins, developers and testers of your app, your use of this endpoint must be reviewed and approved by Facebook. To submit this feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review

From the looks in the source, the 'me/friends' call will still work but the functionality will be different. It could be that Facebook is squawking because since hello.js is using unversioned calls the behavior of the data that gets returned will change in the future and wants to make sure the developers/admins of the app are aware.  In other words, hello.js will still work but what it returns will be different than what you are used to at the moment.

**Comment by MrSwitch** [comment] 2015-03-12 23:09
Thanks @dasper

On an additional note: The default for newly registered apps is to use the latest version of Facebook  Api

**Comment by renholm** [comment] 2015-03-13 14:33
I just got it confirmed from Facebook that it's a bug if you default to v2.0 for unversioned calls and still get the warning. 

> We have managed to reproduce this issue and it appears to be a valid bug. We are assigning this to the appropriate team.

https://developers.facebook.com/bugs/909185112435714/

**Closed** 2015-08-06 21:17 UTC
